name: alpine
on:
  # push:
  workflow_dispatch:
jobs:
  general:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.16
    steps:
      - name: gcompat
        run: |
          apk add gcompat libstdc++ git curl jq # libc6-compat
          uname -a
          printenv
      - uses: actions/checkout@v3
      - name: testspace
        run: |
          curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dbg.tgz | tar -zxvf- -C /usr/local/bin
          testspace -v
          LD_PRELOAD=/lib/libgcompat.so.0 ldd /usr/local/bin/testspace
          # git config --global --add safe.directory $GITHUB_WORKSPACE # see https://github.com/actions/checkout/pull/762
          # git rev-parse HEAD
          # testspace config url ${{github.repository_owner}}.testspace.com --repo=none
          apk add valgrind
          valgrind --leak-check=full testspace help x
          valgrind --leak-check=full testspace config url ${{github.repository_owner}}.testspace.com --repo=none
