name: arm64
on:
  # push:
  workflow_dispatch:
jobs:
  general:
    runs-on: ubuntu-latest
    container:
      image: s2technologies/build-base:centos7
      options: --platform linux/arm64
    steps:
      - name: echo
        run: |
          uname -a
          printenv
      - uses: actions/checkout@v3
      - name: testspace
        run: |
          curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-arm64.tgz | tar -zxvf- -C /usr/local/bin
          testspace -v
