name: macos
on:
  # push:
  workflow_dispatch:
jobs:
  general:
    runs-on: macos-11
    steps:
      - name: echo
        run: |
          uname -a
          printenv
          which gcc
          `which gcc` --version
          `which gcc` -dumpversion
          which llvm-gcc
          `which llvm-gcc` --version
          `which llvm-gcc` -dumpversion
      - uses: actions/checkout@v3
      - name: testspace
        run: |
          curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-darwin.tgz | tar -zxvf- -C /usr/local/bin
          testspace -v
