name: play
on:
  repository_dispatch
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mask
        run: |
          echo "add-mask::${{ format('{0}', github.event.client_payload.p1) }}"
      - name: Use
        run: |
          echo ${{ github.event.client_payload.p1 }}
          echo ${{ github.event.client_payload.p2 }}
          MY_NAME="Mona The Octocat"
          echo "::add-mask::$MY_NAME"
