name: play
on:
  push:
  repository_dispatch:
    types: [testspace]
env:
  X: echo "add-mask::${{ github.event.client_payload.p1 }}"
jobs:
  one:
    if: ${{ github.event.client_payload.function == 'foo' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mask
        run: |
          echo "add-mask::$X"
      - name: Use
        run: |
          echo ${{ github.event.client_payload.p1 }}
          echo ${{ github.event.client_payload.p2 }}
          MY_NAME="Mona The Octocat"
          echo "::add-mask::$MY_NAME"
  general:
    runs-on: ubuntu-latest
    steps:
      - name: Do right
        run: |
          echo "Summary: 43 passed, 0 failed, 5 not applicable, 0 errored, 7684.20 sec."
      - name: Do wrong
        run: |
          echo "::error::Summary: 28 passed, 14 failed, 0 not applicable, 0 errored, 2784.20 sec."
