name: play
on:
  repository_dispatch
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mask
        run: |
          X=$(cat $GITHUB_EVENT_PATH | jq -r ".client_payload.p1")
          echo "add-mask::$X"
      - name: Use
        run: |
          echo ${{ github.event.client_payload.p1 }}
          echo ${{ github.event.client_payload.p2 }}
