name: try
on:
  push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Mask
        run: |
          X=$(cat $GITHUB_EVENT_PATH | jq -r ".before")
          echo "::add-mask::$X"
      - name: Use
        run: |
          echo ${{ github.event.before }}
          echo ${{ github.event.after }}
